---
# Common step for all the projects, define port
server:
    port: 8888

#Step 2: Secure the app    
security:
  basic:
    enabled: true
  user:
    name: test 
    password: test

#Step 1: remote config
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/girirajvyas/springcloud-microservices-tolldata
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern:
              - "*/alternate"
              uri: https://github.com/girirajvyas/springcloud-microservices-tolldata-alternate
              search-paths:
              - 'station*'